#!/usr/bin/env julia
#
# The semi-discrete metriplectic flow: which conservation law comes from which half, and what
# the time discretisation does to each.
#
#     du/dt = P(u) dH/du - G(u) dS/du
#
#     julia --project=scripts scripts/verify_metriplectic_flow.jl
#
# Unlike the other `verify_*` scripts this one uses the package rather than reimplementing the
# object under test.  That is deliberate and it is what the claims are about: the point is not
# that the formulae are right on paper -- `verify_metric_collapse.jl` settles that for the
# bracket -- but that `MetriplecticFlow`, `Integrator` and `entropy_production` as they stand
# reproduce them.  A reimplementation here would verify a second copy.
#
# Four claims, and they fail in four different ways, which is why each gets its own control:
#
#   1. Semi-discrete: Hdot = 0 exactly, on any mesh and at any quadrature order, because
#      G dH/du = 0 -- a property of the *bracket*, not of the integrator.  Sdot <= 0 because G
#      is positive semi-definite.  The control is a bracket generated by the wrong field: it
#      is still symmetric and still semi-definite, and only H notices.
#   2. The Jacobian is analytic.  A central difference is the oracle, and the check is not one
#      tolerance but the SHAPE of the residual against the step: it must fall like eps^2 and
#      then rise like 1/eps, which is what says the floor belongs to the difference scheme.
#   3. `metric_directional` is the O(N^3) derivative tensor contracted, to round-off, and is
#      never slower.  It is an ORDER faster only for the projector bracket, which assembles
#      nothing; for the other two the N perturbed assemblies dominate the N sandwiches that
#      contracting removes, at every size a 2D problem reaches.  That is measured rather than
#      extrapolated, because the plan assumed the order held for all of them.
#   4. Time discretisation: implicit midpoint holds H to round-off, RK4 to its own order, and
#      -- the claim this script exists for -- a Newton iteration stopped on a slack residual
#      tolerance loses the conservation law by orders.  With a lagged Jacobian, convergence is
#      linear, so "stop when the residual is below tau" with tau too large is exactly "stop
#      after a fixed number of iterations", and both cost the same thing.
#

using LinearAlgebra
using PoissonBrackets
using Printf
using Random
using SimpleSplines: UniformMesh, GradedMesh

include(joinpath(@__DIR__, "check.jl"))
using .Checks: header, check, summary

const SEED = 0x6a1d94c3

# ---------------------------------------------------------------------------------------
# The two model problems.
#
# 1D: the projector bracket generated by the field itself (Lambda = I, so phi = u), with
# H = 1/2 int u^2 the Hamiltonian that generates it and S = 1/2 int u_x^2 the dissipated
# quantity.  The flow is a nonlinear heat equation constrained to the sphere H = const.
#
# 2D: the double and collision brackets generated by the screened Poisson solve
# psihat = (K + M/2)^{-1} M omegahat, so dH/du = M Lambda u with M Lambda symmetric -- Lambda
# really is M^{-1} dH/du of a Hamiltonian -- and S = 1/2 int u^2.
# ---------------------------------------------------------------------------------------

function problem_1d(N = 16; mesh = UniformMesh(N, 2π), nq = 4)
    s = SplineSpace(mesh, 3; nq = nq)
    n = nbasis(s)
    Λ = Matrix{Float64}(I, n, n)
    (space = s,
        bracket = ProjectorBracket(s, Λ),
        H = QuadraticHamiltonian(Matrix(mass_matrix(s))),
        S = QuadraticHamiltonian(Matrix(stiffness_matrix(s))))
end

function problem_2d(n = 5)
    s = TensorSplineSpace((n, n), 2)
    M = Matrix(mass_matrix(s))
    Λ = (Matrix(stiffness_matrix(s)) + 0.5M) \ M
    (space = s, Λ = Λ,
        H = QuadraticHamiltonian(M * Λ),
        S = QuadraticHamiltonian(M))
end

function metric_brackets_2d(p)
    ("double" => DoubleBracket(p.space, p.Λ),
        "projector" => ProjectorBracket(p.space, p.Λ),
        "collision" => CollisionBracket(p.space, p.Λ),
        "collision, M(u) = 1 + u^2" => CollisionBracket(p.space, p.Λ;
            mobility = (x, u) -> 1 + u^2, mobility_derivative = (x, u) -> 2u))
end

# Hdot and Sdot from the definitions, not from the flow: the gradient of each quantity
# contracted with the vector field the flow reports.
function rates(f, û)
    (dot(gradient(f, û), vectorfield(f, û)),
        dot(PoissonBrackets.entropy_gradient(f, û), vectorfield(f, û)))
end

function finite_difference_jacobian(f, û, ε)
    N = length(û)
    J = zeros(N, N)
    for m in 1:N
        e = zeros(N)
        e[m] = ε
        J[:, m] = (vectorfield(f, û .+ e) .- vectorfield(f, û .- e)) ./ 2ε
    end
    return J
end

function contracted_derivative(b, û, v)
    dG = metric_derivative(b, û)
    N = length(û)
    [sum(dG[m, i, j] * v[j] for j in 1:N) for i in 1:N, m in 1:N]
end

# ---------------------------------------------------------------------------------------

let rng = MersenneTwister(SEED)
    header("1. semi-discrete: H is exact, S is monotone, on any mesh and any n_q")

    # The mesh and the quadrature order are varied together because the claim is that neither
    # enters.  H is conserved by antisymmetry and degeneracy alone; no property of the rule
    # is used, which is why n_q = 2 below is not a mistake.
    worstH = 0.0
    worstS = -Inf
    for mk in (UniformMesh(16, 2π), GradedMesh(16, 2π)), nq in (2, 4, 6)

        p = problem_1d(; mesh = mk, nq = nq)
        f = MetriplecticFlow(p.space, p.bracket, p.H, p.S)
        for _ in 1:20
            û = 0.3 .* randn(rng, nbasis(p.space))
            Ḣ, Ṡ = rates(f, û)
            scale = max(1.0, maximum(abs, gradient(f, û)) * maximum(abs, vectorfield(f, û)))
            worstH = max(worstH, abs(Ḣ) / scale)
            worstS = max(worstS, Ṡ / scale)
        end
    end
    check("H is conserved on 2 meshes x 3 quadrature orders", worstH < 1e-14,
        @sprintf("worst normalised |Hdot| = %.2e over 120 states", worstH))
    check("S is non-increasing on all of them", worstS <= 0,
        @sprintf("worst normalised Sdot = %.2e", worstS))

    # The Poisson half does not touch the statement about H.
    p = problem_1d()
    fp = MetriplecticFlow(p.space, kdv_bracket_1(p.space), p.bracket, p.H, p.S)
    worstHp = 0.0
    for _ in 1:100
        û = 0.3 .* randn(rng, nbasis(p.space))
        Ḣ, _ = rates(fp, û)
        scale = max(1.0, maximum(abs, gradient(fp, û)) * maximum(abs, vectorfield(fp, û)))
        worstHp = max(worstHp, abs(Ḣ) / scale)
    end
    check("H survives adding the Poisson half", worstHp < 1e-14,
        @sprintf("worst normalised |Hdot| = %.2e", worstHp))

    # It does touch the statement about S, and the size of {S,H} is a statement about the
    # MESH rather than an identity -- exactly as for the KdV cross-conservation
    # {H2,H1}_1 = 0.  Both S and H here are quadratic forms in circulant operators on a
    # uniform mesh, and quadratic forms in commuting circulants Poisson-commute; grade the
    # mesh and they do not.  A check written on a uniform mesh alone would have concluded
    # that the Poisson half never disturbs S, which is false.
    function worst_ph(mesh)
        q = problem_1d(; mesh = mesh)
        g = MetriplecticFlow(q.space, kdv_bracket_1(q.space), q.bracket, q.H, q.S)
        w = 0.0
        for _ in 1:50
            û = 0.3 .* randn(rng, nbasis(q.space))
            ph = poisson_apply(kdv_bracket_1(q.space), û, gradient(g, û))
            w = max(w,
                abs(dot(PoissonBrackets.entropy_gradient(g, û), ph)) /
                (maximum(abs, PoissonBrackets.entropy_gradient(g, û)) *
                 maximum(abs, ph) * nbasis(q.space)))
        end
        return w
    end
    uni, graded = worst_ph(UniformMesh(16, 2π)), worst_ph(GradedMesh(16, 2π))
    check("{S,H} vanishes on a UNIFORM mesh -- circulance, not an identity", uni < 1e-14,
        @sprintf("worst normalised {S,H} = %.2e over 50 states", uni))
    check("and does NOT on a graded one", graded > 1e-4,
        @sprintf("worst normalised {S,H} = %.2e, %.0e times larger", graded, graded / uni))

    # The control.  A bracket generated by the wrong field is still symmetric and still
    # positive semi-definite -- a rank-one correction to M^{-1} is one whatever phi is -- and
    # only the degeneracy, hence only H, notices.
    s = p.space
    wrong = ProjectorBracket(s, project(s, x -> cos(3x) + 2))
    fw = MetriplecticFlow(s, wrong, p.H, p.S)
    bestw = Inf
    for _ in 1:100
        û = 0.3 .* randn(rng, nbasis(s))
        Ḣ, _ = rates(fw, û)
        scale = max(1.0, maximum(abs, gradient(fw, û)) * maximum(abs, vectorfield(fw, û)))
        bestw = min(bestw, abs(Ḣ) / scale)
    end
    check("a bracket generated by the WRONG field loses H", bestw > 1e-3,
        @sprintf("best normalised |Hdot| = %.2e, still O(1)", bestw))
    check("and it is symmetric and semi-definite regardless",
        issymmetric(wrong, zeros(nbasis(s))) &&
            ispositive_semidefinite(wrong, zeros(nbasis(s))),
        "so neither of those two tests can catch it")
end

let rng = MersenneTwister(SEED + 1)
    header("2. the Jacobian is analytic: the residual floor belongs to the difference")

    p = problem_1d()
    f = MetriplecticFlow(p.space, p.bracket, p.H, p.S)
    û = 0.3 .* randn(rng, nbasis(p.space))
    J = jacobian(f, û)
    scale = maximum(abs, J)

    # Refine the step.  A residual that is a defect of the derivative would be flat; one that
    # is the difference scheme's own error falls like eps^2 until round-off takes over and
    # then rises like 1/eps.  The V is the evidence, not the minimum.
    εs = [1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8]
    res = [maximum(abs, J - finite_difference_jacobian(f, û, ε)) / scale for ε in εs]
    for (ε, r) in zip(εs, res)
        check(@sprintf("  eps = %.0e", ε), true, @sprintf("relative residual %.2e", r))
    end
    k = argmin(res)
    check("the residual falls like eps^2 before the minimum",
        k > 1 && res[1] / res[k] > 1e3,
        @sprintf("%.2e at eps=1e-3 down to %.2e at eps=%.0e", res[1], res[k], εs[k]))
    check("and rises again after it: round-off, not the derivative",
        k < length(res) && res[end] > 10 * res[k],
        @sprintf("%.2e at eps=1e-8", res[end]))

    # Every 2D bracket, at the minimum only.
    q = problem_2d()
    v = 0.3 .* randn(rng, nbasis(q.space))
    for (name, b) in metric_brackets_2d(q)
        g = MetriplecticFlow(q.space, b, q.H, q.S)
        Jb = jacobian(g, v)
        r = maximum(abs, Jb - finite_difference_jacobian(g, v, 1e-6)) / maximum(abs, Jb)
        check("the $(name) bracket's flow differentiates analytically", r < 1e-6,
            @sprintf("relative residual %.2e at eps = 1e-6", r))
    end
end

let rng = MersenneTwister(SEED + 2)
    header("3. metric_directional is the derivative tensor, contracted -- and cheaper")

    q = problem_2d()
    N = nbasis(q.space)
    û = 0.3 .* randn(rng, N)
    v = randn(rng, N)

    for (name, b) in metric_brackets_2d(q)
        D = PoissonBrackets.metric_directional(b, û, v)
        Dfull = contracted_derivative(b, û, v)
        r = maximum(abs, D - Dfull) / maximum(abs, Dfull)
        check("the $(name) bracket agrees with the O(N^3) tensor", r < 1e-12,
            @sprintf("relative %.2e, against a tensor of size %.1e", r,
                maximum(abs, Dfull)))
    end

    # The cost, which is the reason the contracted path exists -- and it is not the same story
    # for all three brackets, so the SCALING is measured rather than one ratio quoted.  What
    # contracting removes is the N mass sandwiches, O(N^3) each; what it cannot remove is the
    # N perturbed assemblies, which both paths pay.  So the saving is an order only where the
    # assemblies are cheap or absent.
    function ratio(b, n)
        s = TensorSplineSpace((n, n), 2)
        M = Matrix(mass_matrix(s))
        Λ = (Matrix(stiffness_matrix(s)) + 0.5M) \ M
        bracket = b(s, Λ)
        x = 0.3 .* randn(MersenneTwister(SEED + 3), nbasis(s))
        y = randn(MersenneTwister(SEED + 4), nbasis(s))
        PoissonBrackets.metric_directional(bracket, x, y)            # warm up both paths
        contracted_derivative(bracket, x, y)
        td = minimum(@elapsed(PoissonBrackets.metric_directional(bracket, x, y))
        for _ in 1:3)
        tt = minimum(@elapsed(contracted_derivative(bracket, x, y)) for _ in 1:3)
        (nbasis(s), td, tt, tt / td)
    end

    for (name, ctor) in ("projector" => ProjectorBracket, "double" => DoubleBracket,
        "collision" => CollisionBracket)
        rs = [ratio(ctor, n) for n in (5, 9)]
        check("  $(name): N = $(rs[1][1]) -> $(rs[2][1])", true,
            @sprintf("speedup %.0fx -> %.0fx  (%.2f ms against %.2f ms at the larger)",
                rs[1][4], rs[2][4], 1e3rs[2][2], 1e3rs[2][3]))
    end

    # The closed form is the case where the saving really is an order: no assembly at all, so
    # nothing is left to dominate the sandwich it removes.
    rp = [ratio(ProjectorBracket, n) for n in (5, 9, 11)]
    check("the projector bracket's saving GROWS with N: a closed form",
        rp[end][4] > 5 * rp[1][4],
        @sprintf("%.0fx at N=%d rising to %.0fx at N=%d",
            rp[1][4], rp[1][1], rp[end][4], rp[end][1]))
    # The other two are bounded by their own assemblies at reachable N, and saying otherwise
    # would be an extrapolation rather than a measurement.  The contracted path is still never
    # slower, which is the claim that is actually load-bearing inside Newton.
    rd = [ratio(DoubleBracket, n) for n in (5, 11)]
    rc = [ratio(CollisionBracket, n) for n in (5, 11)]
    check("the assembled ones are never slower, but not an order faster here",
        rd[end][4] > 1 && rc[end][4] > 1 && rd[end][4] < 5 && rc[end][4] < 5,
        @sprintf("double %.1fx, collision %.1fx at N = %d -- the N assemblies dominate",
            rd[end][4], rc[end][4], rd[end][1]))
end

let
    header("4. time discretisation, and why Newton needs a residual tolerance")

    p = problem_1d()
    s = p.space
    f = MetriplecticFlow(s, p.bracket, p.H, p.S)
    u0 = project(s, x -> sin(x) + 0.3cos(2x)^2)
    H0 = hamiltonian(p.H, s, u0)
    Δt = 1e-3
    nsteps = 200

    # `sin` alone is an eigenfunction of -d_x^2, so dS/du would be parallel to dH/du and land
    # in the kernel: the whole vector field would be 1e-13 and every check below vacuous.
    check("the initial condition excites the bracket at all",
        maximum(abs, vectorfield(f, u0)) > 1,
        @sprintf("|f(u0)| = %.2f, against %.1e for sin alone",
            maximum(abs, vectorfield(f, u0)),
            maximum(abs, vectorfield(f, project(s, sin)))))

    function run(integ, n = nsteps)
        û = copy(u0)
        dH = 0.0
        Ss = [hamiltonian(p.S, s, û)]
        prod = Float64[]
        for _ in 1:n
            integrate_step!(û, integ)
            dH = max(dH, abs(hamiltonian(p.H, s, û) - H0))
            push!(Ss, hamiltonian(p.S, s, û))
            push!(prod, entropy_production(f, û))
        end
        (drift = dH / abs(H0), S = Ss, production = prod, final = û)
    end

    mid = run(Integrator(f, ImplicitMidpoint(), Δt; û₀ = u0))
    rk4 = run(Integrator(f, RungeKutta4(), Δt))

    check("implicit midpoint holds H to round-off", mid.drift < 1e-14,
        @sprintf("relative drift %.2e over %d steps", mid.drift, nsteps))
    check("RK4 holds it only to its own order", 1e-14 < rk4.drift < 1e-8,
        @sprintf("relative drift %.2e, %.0fx the midpoint rule's",
            rk4.drift, rk4.drift / mid.drift))
    check("S falls at every step, under both",
        all(<(0), diff(mid.S)) && all(<(0), diff(rk4.S)),
        @sprintf("S: %.4f -> %.4f", mid.S[1], mid.S[end]))
    check("entropy production is positive throughout", all(>(0), mid.production),
        @sprintf("smallest %.3f, largest %.3f",
            minimum(mid.production), maximum(mid.production)))
    check("and the two methods integrate the same field",
        maximum(abs, mid.final .- rk4.final) < 1e-4 * maximum(abs, mid.final),
        @sprintf("relative difference %.2e after %d steps",
            maximum(abs, mid.final .- rk4.final) / maximum(abs, mid.final), nsteps))

    # THE claim.  The conservation of H rests on the *converged* midpoint increment lying in
    # the range of G(ubar).  An unconverged one does not, and with a lagged Jacobian the
    # convergence is linear, so a slack tolerance is not a small compromise.
    header("   the residual tolerance is what buys the conservation law")
    τ0 = default_f_abstol(Float64, nbasis(s), u0)
    drifts = [(τ, run(Integrator(f, ImplicitMidpoint(), Δt; f_abstol = τ), 50).drift)
              for τ in (τ0, 1e-12, 1e-10, 1e-8, 1e-6)]
    for (τ, d) in drifts
        check(@sprintf("  f_abstol = %.1e", τ), true, @sprintf("relative drift in H %.2e",
            d))
    end
    check("a slack tolerance costs orders of magnitude in H",
        last(drifts)[2] > 1e4 * first(drifts)[2],
        @sprintf("%.2e at 1e-6 against %.2e at the default %.1e",
            last(drifts)[2], first(drifts)[2], τ0))
    check("and the degradation is monotone in the tolerance",
        issorted([d for (_, d) in drifts]),
        "so it is the residual that is being traded, not noise")
end

summary("verify_metriplectic_flow.jl")
