
@doc raw"""
    HamiltonianFlow(space, bracket, hamiltonian)

The semi-discrete system generated by contracting a [`DiscreteBracket`](@ref) with the
gradient of a [`DiscreteHamiltonian`](@ref),

```math
\dot{\hat{u}} = \mathbb{P} (\hat{u}) \, \frac{\partial H}{\partial \hat{u}} (\hat{u}) .
```

```jldoctest
julia> s = SplineSpace(16, 3);

julia> f = HamiltonianFlow(s, kdv_bracket_1(s), KdVHamiltonian1());

julia> û = project(s, sin);

julia> length(vectorfield(f, û))
16
```

# Conservation

Two things are conserved by the semi-discrete flow, exactly and on any mesh:

  - the **generating** Hamiltonian, because
    ``\dot{H} = (\partial H/\partial \hat{u})^T \mathbb{P} (\partial H/\partial \hat{u})``
    vanishes by antisymmetry alone — no property of the quadrature is needed, which is
    exactly what the skew-symmetrised assembly buys;
  - the **mass**, for the reasons given at [`MassCasimir`](@ref).

The *other* Hamiltonian of a bi-Hamiltonian pair is not conserved, and the reason is worth
stating precisely, because it is easy to mistake for a defect of the integrator: the
semi-discrete cross-conservation ``\{H_2, H_1\}_1 = 0`` is not an identity in the degrees of
freedom. Its quadratic part vanishes for every ``\hat{u}`` on a uniform mesh, but its cubic
part vanishes only for resolved fields. A time integrator can inherit identities; it cannot
inherit a statement about which modes happen to be resolved.
"""
struct HamiltonianFlow{T, ST <: DiscreteSpace{T}, BT <: DiscreteBracket{T},
    HT <: DiscreteHamiltonian{T}}
    space::ST
    bracket::BT
    hamiltonian::HT
end

Base.eltype(::HamiltonianFlow{T}) where {T} = T
Base.length(f::HamiltonianFlow) = nbasis(f.space)

space(f::HamiltonianFlow) = f.space
bracket(f::HamiltonianFlow) = f.bracket
hamiltonian(f::HamiltonianFlow) = f.hamiltonian

hamiltonian(f::HamiltonianFlow, û::AbstractVector) = hamiltonian(f.hamiltonian, f.space, û)
gradient(f::HamiltonianFlow, û::AbstractVector) = gradient(f.hamiltonian, f.space, û)
hessian(f::HamiltonianFlow, û::AbstractVector) = hessian(f.hamiltonian, f.space, û)

"""
    vectorfield(flow, û)

The right-hand side ``\\mathbb{P}(\\hat{u}) \\, \\partial H / \\partial \\hat{u}``.
"""
function vectorfield(f::HamiltonianFlow, û::AbstractVector)
    poisson_apply(f.bracket, û, gradient(f, û))
end

"""
    vectorfield!(du, flow, û)

In-place [`vectorfield`](@ref).
"""
function vectorfield!(du::AbstractVector, f::HamiltonianFlow, û::AbstractVector)
    (du .= vectorfield(f, û); du)
end

@doc raw"""
    jacobian(flow, û)

The Jacobian ``\partial \dot{\hat{u}}_i / \partial \hat{u}_m`` of the vector field.

Differentiating ``f_i = \sum_j \mathbb{P}_{ij}(\hat{u}) \, g_j(\hat{u})`` gives two terms,

```math
\frac{\partial f_i}{\partial \hat{u}_m}
  = \left( \mathbb{P} \, H'' \right)_{im}
  + \sum_j \frac{\partial \mathbb{P}_{ij}}{\partial \hat{u}_m} \, g_j ,
```

the second of which is [`bracket_directional`](@ref). It vanishes for a constant bracket
and is available in closed form for the others, so no ``O(N^3)`` tensor is formed here.

The Jacobian is analytic throughout. A central difference has a floor around ``10^{-10}`` on
these problems, and the Poisson-map defect of a symplectic method sits three orders below
that — so a finite-difference Jacobian would measure its own truncation error and report it
as a violation of the Poisson property.
"""
function jacobian(f::HamiltonianFlow, û::AbstractVector)
    J = poisson_matrix(f.bracket, û) * hessian(f, û)
    add_bracket_term!(J, f.bracket, û, gradient(f, û))
end

"""
    add_bracket_term!(J, bracket, û, g)

Add [`bracket_directional`](@ref)`(bracket, û, g)` to `J` in place.

Dispatching the second term of the Jacobian on the *bracket* rather than on the flow keeps
the specialisations unambiguous, and lets the brackets that contribute nothing skip
building an `N × N` matrix of zeros on every Newton iteration.
"""
function add_bracket_term!(J::AbstractMatrix, b::DiscreteBracket, û, g)
    (J .+= bracket_directional(b, û, g); J)
end

add_bracket_term!(J::AbstractMatrix, ::ConstantBracket, û, g) = J
