
@doc raw"""
    MetriplecticFlow(space, bracket, metric, hamiltonian, entropy)
    MetriplecticFlow(space, metric, hamiltonian, entropy)

The semi-discrete system generated by a [`DiscreteBracket`](@ref) and a
[`MetricBracket`](@ref) together,

```math
\dot{\hat{u}} = \mathbb{P} (\hat{u}) \, \frac{\partial H}{\partial \hat{u}} (\hat{u})
              - \mathbb{G} (\hat{u}) \, \frac{\partial S}{\partial \hat{u}} (\hat{u}) .
```

The four-argument form leaves out the Poisson half, which is the case the manuscript's
experiments actually run: `bracket === nothing` and the field is purely dissipative. The
general form is written out here regardless, because it is what says which conservation law
comes from which half.

```jldoctest
julia> s = SplineSpace(16, 3);

julia> Λ = [i == j ? 1.0 : 0.0 for i in 1:16, j in 1:16];   # δH/δu = u, so φ̂ = û

julia> f = MetriplecticFlow(s, ProjectorBracket(s, Λ),
                            QuadraticHamiltonian(Matrix(mass_matrix(s))),
                            QuadraticHamiltonian(Matrix(stiffness_matrix(s))));

julia> û = project(s, x -> sin(x) + 0.3cos(2x)^2);

julia> abs(sum(gradient(f, û) .* vectorfield(f, û))) < 1e-12
true
```

The initial condition is deliberately not ``\sin``: with ``S`` the Dirichlet energy on a
periodic domain, ``\sin`` is an eigenfunction of ``-\partial_x^2``, so
``\partial S/\partial \hat{u}`` is parallel to ``\partial H/\partial \hat{u}`` and lands in
the kernel of ``\mathbb{G}``. The whole vector field is then ``10^{-13}`` and the check above
would hold of nothing at all.

# Conservation, and which half is responsible

Two statements, and they are independent:

  - ``H`` is conserved **exactly**, on any mesh, because the metric bracket is degenerate on
    it: ``\dot{H} = (\partial H/\partial \hat{u})^T \mathbb{P} (\partial H/\partial \hat{u})
    - (\mathbb{G} \, \partial H/\partial \hat{u})^T \partial S/\partial \hat{u}``, whose first
    term vanishes by antisymmetry and whose second vanishes by
    [`degeneracy_residual`](@ref) being zero. Neither term needs a property of the quadrature.
  - ``S`` is **monotone**, because ``\dot{S} = - (\partial S/\partial \hat{u})^T \mathbb{G}
    (\partial S/\partial \hat{u}) \le 0`` by positive semi-definiteness alone; the Poisson
    half contributes ``\{S, H\}`` to it, which does not vanish in general. See
    [`entropy_production`](@ref).

The sign convention is the one in the display above, so ``S`` **decreases**. That is what
makes the sign meaningful rather than a matter of taste: with ``\mathbb{G}`` positive
semi-definite, ``+\mathbb{G} \, \partial S/\partial \hat{u}`` would be a backward heat
equation. A quantity that is to increase along the flow is passed as its own negative.

# What it takes to integrate one

[`RungeKutta4`](@ref) covers the explicit cases and [`ImplicitMidpoint`](@ref) — which for
this field is Crank-Nicolson — the implicit ones, both through the ordinary
[`Integrator`](@ref) and its `SimpleSolvers.NewtonSolver`. Nothing about the nonlinear solve
is special here.

!!! warning "Newton must be iterated to a residual tolerance"
    Not to a fixed iteration count. The solver reuses a lagged Jacobian
    (`refactorize`), so its convergence is only linear, and a count chosen from how a full
    Newton behaves stops short by orders of magnitude. What is then lost is exactly the
    property the flow exists for: ``H`` is conserved because the *converged* midpoint
    increment lies in the range of ``\mathbb{G}(\bar{u})``, and an unconverged one does not.
    See [`default_f_abstol`](@ref) for how the tolerance is set.

The [`Gonzalez`](@ref) discrete-gradient methods are not available: see
[`AbstractFlow`](@ref).
"""
struct MetriplecticFlow{
    T, ST <: DiscreteSpace{T}, BT <: Union{Nothing, DiscreteBracket{T}},
    GT <: MetricBracket{T}, HT <: DiscreteHamiltonian{T},
    ET <: DiscreteHamiltonian{T}} <: AbstractFlow{T}
    space::ST
    bracket::BT
    metric::GT
    hamiltonian::HT
    entropy::ET
end

function MetriplecticFlow(s::DiscreteSpace, G::MetricBracket, H::DiscreteHamiltonian,
        S::DiscreteHamiltonian)
    MetriplecticFlow(s, nothing, G, H, S)
end

Base.eltype(::MetriplecticFlow{T}) where {T} = T
Base.length(f::MetriplecticFlow) = nbasis(f.space)

space(f::MetriplecticFlow) = f.space
bracket(f::MetriplecticFlow) = f.bracket
metric(f::MetriplecticFlow) = f.metric
hamiltonian(f::MetriplecticFlow) = f.hamiltonian

hamiltonian(f::MetriplecticFlow, û::AbstractVector) = hamiltonian(f.hamiltonian, f.space, û)
gradient(f::MetriplecticFlow, û::AbstractVector) = gradient(f.hamiltonian, f.space, û)
hessian(f::MetriplecticFlow, û::AbstractVector) = hessian(f.hamiltonian, f.space, û)

"""
    entropy(flow)
    entropy(flow, û)
    entropy_gradient(flow, û)
    entropy_hessian(flow, û)

The dissipated quantity of a [`MetriplecticFlow`](@ref), and its value, gradient and Hessian
at `û`.

The Hamiltonian half of the same flow is reached through [`hamiltonian`](@ref),
[`gradient`](@ref) and [`hessian`](@ref), which is what the integrators call; the entropy
needs its own three names because both are `DiscreteHamiltonian`s and only the flow knows
which is which.
"""
entropy(f::MetriplecticFlow) = f.entropy

entropy(f::MetriplecticFlow, û::AbstractVector) = hamiltonian(f.entropy, f.space, û)

@doc (@doc entropy)
entropy_gradient(f::MetriplecticFlow, û::AbstractVector) = gradient(f.entropy, f.space, û)

@doc (@doc entropy)
entropy_hessian(f::MetriplecticFlow, û::AbstractVector) = hessian(f.entropy, f.space, û)

@doc raw"""
    vectorfield(f::MetriplecticFlow, û)

The right-hand side ``\mathbb{P}(\hat{u}) \, \partial H/\partial \hat{u}
- \mathbb{G}(\hat{u}) \, \partial S/\partial \hat{u}``.

Both halves are formed through [`poisson_apply`](@ref) and [`metric_apply`](@ref), so neither
matrix is assembled where the bracket admits a matrix-free contraction — which for the metric
brackets is the difference between ``O(NQ)`` and ``O(N^3)`` per evaluation.
"""
function vectorfield(f::MetriplecticFlow, û::AbstractVector)
    v = -metric_apply(f.metric, û, entropy_gradient(f, û))
    _add_poisson_term!(v, f.bracket, f, û)
end

"""
    _add_poisson_term!(v, bracket, flow, û)

Add the Hamiltonian half to `v` in place.

Dispatching on the bracket rather than branching on `nothing` is what lets the purely
dissipative flow — the one the experiments run — skip the contraction entirely rather than
contract against a bracket of zeros.
"""
_add_poisson_term!(v::AbstractVector, ::Nothing, f::MetriplecticFlow, û) = v

function _add_poisson_term!(v::AbstractVector, b::DiscreteBracket, f::MetriplecticFlow, û)
    (v .+= poisson_apply(b, û, gradient(f, û)); v)
end

@doc raw"""
    jacobian(f::MetriplecticFlow, û)

The Jacobian ``\partial \dot{\hat{u}}_i / \partial \hat{u}_m`` of the vector field, analytic
throughout.

Each half differentiates into two terms by the product rule,

```math
\frac{\partial f_i}{\partial \hat{u}_m}
  = \left( \mathbb{P} \, H'' \right)_{im}
  + \sum_j \frac{\partial \mathbb{P}_{ij}}{\partial \hat{u}_m} \,
      \frac{\partial H}{\partial \hat{u}_j}
  - \left( \mathbb{G} \, S'' \right)_{im}
  - \sum_j \frac{\partial \mathbb{G}_{ij}}{\partial \hat{u}_m} \,
      \frac{\partial S}{\partial \hat{u}_j} ,
```

the second of which is [`bracket_directional`](@ref) and the fourth
[`metric_directional`](@ref). Neither ``O(N^3)`` derivative tensor is formed: the whole point
of contracting first is that a Newton iteration only ever needs the tensor against one
direction.

Finite differences are not an alternative here, and not for the usual reason about accuracy.
A central difference has a floor around ``10^{-10}`` on these problems, while the quantity the
flow exists to preserve — the drift in ``H`` under the converged implicit step — sits at
round-off, so a differenced Jacobian would perturb the Newton iterate by more than the
conservation law it is supposed to leave alone.
"""
function jacobian(f::MetriplecticFlow, û::AbstractVector)
    g = entropy_gradient(f, û)
    J = -Matrix(metric_matrix(f.metric, û) * entropy_hessian(f, û))
    J .-= metric_directional(f.metric, û, g)
    _add_poisson_jacobian!(J, f.bracket, f, û)
end

"""
    _add_poisson_jacobian!(J, bracket, flow, û)

Add the Hamiltonian half of [`jacobian`](@ref) to `J` in place, both of its terms.
"""
_add_poisson_jacobian!(J::AbstractMatrix, ::Nothing, f::MetriplecticFlow, û) = J

function _add_poisson_jacobian!(J::AbstractMatrix, b::DiscreteBracket, f::MetriplecticFlow, û)
    J .+= poisson_matrix(b, û) * hessian(f, û)
    add_bracket_term!(J, b, û, gradient(f, û))
end
